#!/bin/bash

## Move into the right directory
cd `dirname $0`

echo This will install freja in your account.
echo The installation operations include:
echo '*' Place files for freja in $HOME/.freja
echo '*' Place a link to freja executable in $HOME/.local/bin
## Update the shell
case "`getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev`" in
	"bash")
		echo '*' Update $HOME/.bash_profile to add $HOME/.local/bin to \$PATH
	;;
	"tcsh")
		echo '*' Update $HOME/.cshrc to add $HOME/.local/bin to \$PATH
	;;
	*)
		:
	;;
esac
echo Continue '(y/[n])'?
read proceed

shell_comment='## Add the local hierarchy ~/.local/bin (that contains freja executable) into $PATH'
shell_var=PATH
shell_val=$HOME/.local/bin

install_bash()
{
	## Backup $HOME/.bash_profile
	if [ -f $HOME/.bash_profile ]
	then
		echo Create backup for $HOME/.bash_profile in $HOME/.bash_profile.freja.$$.bak
		cp $HOME/.bash_profile $HOME/.bash_profile.freja.$$.bak
	fi

	echo >> $HOME/.bash_profile
	echo $shell_comment >> $HOME/.bash_profile
	echo export $shell_var='$'"$shell_var:$shell_val" >> $HOME/.bash_profile
}

install_csh()
{
	## Backup $HOME/.schrc
	if [ -f $HOME/.cshrc ]
	then
		echo Create backup for $HOME/.cshrc in $HOME/.cshrc.freja.$$.bak
		cp $HOME/.cshrc $HOME/.cshrc.freja.$$.bak
	fi

	echo >> $HOME/.cshrc
	echo $shell_comment >> $HOME/.cshrc
	echo >> $HOME/.cshrc
	echo 'if ($?'$shell_var') then' >> $HOME/.cshrc
	echo '	setenv' $shell_var '${'"$shell_var}:$shell_val" >> $HOME/.cshrc
	echo 'else' >> $HOME/.cshrc
	echo '	setenv' "$shell_var $shell_val" >> $HOME/.cshrc
	echo 'endif' >> $HOME/.cshrc
}

if [ "$proceed" == "y" ]
then
	## Create directories, if needed
	mkdir -p $HOME/.local/bin
	mkdir -p $HOME/.freja

	## Copy freja's files
	cp freja/* $HOME/.freja
	if [ ! -f $HOME/.local/bin/freja ]
	then
		ln -s $HOME/.freja/freja $HOME/.local/bin/
	fi

	## Update the shell
	case "`getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev`" in
		"bash")
			install_bash
		;;
		"tcsh")
			install_csh
		;;
		*)
			echo '[WARN]' Don"'"t know how to setup `getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev` to update $shell_var at startup.
		;;
	esac

	echo Installation done.
	echo
	echo End your session and login again to reflect the change.
else
	echo No change performed
fi
