#!/bin/bash

# Copyright 2015 Nicolas Melot
#
# This file is part of Freja.
#
# Freja is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Freja is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Freja. If not, see <http://www.gnu.org/licenses/>.
#

log()
{
	if [ "$dryrun" == "0" ] || [ "$dryrun" == "" ]
	then
		echo "  "$@
		eval $@
	else
		echo "  "$@
	fi
}

usage()
{
	echo
	echo "	$0 "'[ --prefix ] [ --configure ]'
	echo "		--prefix			Base directory where to install Freja. Will install executable"
	echo "							$prefix/bin/freja and configuration files in $prefix/share/freja/"
	echo "		--configure			Add $prefix/bin to PATH at Bash or tcsh session startup, depending on system"
	echo "		-n | --not-really | --dryrun	Displays operations to run, but do not really perform them"
	echo
	echo
}

parse_options()
{
	while [[ $# > 0 ]]
	do
		case "$1" in
			"--configure")
				configure=1
			;;
			"-n" | "--dryrun" | "--not-really")
				dryrun=1
			;;
			"--prefix")
				shift
				prefix="$1"
			;;
			*)
				usage
				exit 0
			;;
		esac
		## Get to next argument
		shift
	done
}

## Default values
prefix=$HOME/.local

## Parse all options
eval parse_options `for i in "$@"; do printf "\"%s\" " "$(echo $i|sed 's/"/\\\"/g')"; done; echo`

## Move into the right directory
cd `dirname $0`

echo This will install freja in your account.
echo The installation operations include:
echo '*' Place configuration files for freja in $prefix/share/freja
if [ "$configure" != "0" ] && [ "$configure" != "" ]
then
	## Update the shell
	case "`getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev`" in
		"bash")
			echo '*' Update $HOME/.bash_profile to add $prefix/bin to \$PATH
			echo '*' Update $HOME/.bashrc to add $prefix/bin to \$PATH
		;;
		"tcsh")
			echo '*' Update $HOME/.cshrc to add $prefix/bin to \$PATH
		;;
		*)
			:
		;;
	esac
fi
echo '*' Place freja executable in $prefix/bin
echo Continue '(y/[n])'?
read proceed

shell_comment='\#\# Add the local hierarchy ~/.local/bin \(that contains freja executable\) into \$PATH'
shell_var=PATH
shell_val=$prefix/bin

install_bash()
{
	## $1 is the file in which we want to output the additional commands
	filename="$1"

	## Backup $HOME/.bash_profile
	if [ -f "$filename" ]
	then
		echo Create backup for $filename in ${filename}.freja.$$.bak
		log 'cp "'$filename'" "'${filename}.freja.$$.bak'"'
	fi

	log "echo >> $filename"
	log "echo $shell_comment >> $filename"
	log "echo export $shell_var='$'\"$shell_var:$shell_val\" >> $filename"
}

install_csh()
{
	## $1 is the file in which we want to output the additional commands
	filename="$1"

	## Backup $HOME/.schrc
	if [ -f "$filename" ]
	then
		echo Create backup for $filename in ${filename}.cshrc.freja.$$.bak
		log 'cp $filename ${filename}.freja.$$.bak'
	fi

	log "echo >> $filename"
	log "echo $shell_comment >> $filename"
	log "echo 'if (\$?'$shell_var') then' >> $filename"
	log "echo 	setenv $shell_var \""'\${'"$shell_var"'}'":$shell_val\" >> $filename"
	log "echo 'else' >> $filename"
	log "echo '	setenv' "$shell_var $shell_val" >> $filename"
	log "echo 'endif' >> $filename"
}

if [ "$proceed" == "y" ]
then
	## Create directories, if needed
	log "mkdir -p $prefix/bin"
	log "mkdir -p $prefix/share/freja"

	## Copy freja's files
	log "cp share/* $prefix/share/freja"
	log "cp bin/* $prefix/bin/"

	## Update the shell
	if [ "$configure" != "0" ] && [ "$configure" != "" ]
	then
		case "`getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev`" in
			"bash")
				install_bash $HOME/.bash_profile
				install_bash $HOME/.bashrc
			;;
			"tcsh")
				install_csh $HOME/.cshrc
			;;
			*)
				echo '[WARN]' Requested startup configuration but cannot configure \""`getent passwd $LOGNAME | cut -d: -f7 | rev | cut -f 1 -d '/' | rev`"\" shell.
			;;
		esac
	fi

	echo Installation done.
	echo
	
	if [ "$dryrun" == "0" ] || [ "$dryrun" == "" ]
	then
		echo End your session and login again to reflect the change.
	else
		echo Run again without dry run to really install Freja
	fi
else
	echo No change performed
fi
