#!/bin/bash

#     Copyright 2011 Nicolas Melot
# 
#    Nicolas Melot (nicolas.melot@liu.se)
# 
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
# 
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Variable and alias name format:
# Forbidden character: !=<>:&|()+-*/ (may be more characters raising issues. Stick to a-zA-Z0-9_~{}^ and ' '
# Special characters: ~^{}  ~ is replaced by _ and are interpreted for exposants and indices as latex does.
#	Note: You *MUST* use them in the processing and plotting scripts to address these columns and aliases
# Must not begin with a digit 0-9 or a point '.' and must not start or finish with a space ' '.

# Never use these names for run or compile features (please report other problematic names)
# count

## Compile-time settings
compile=(entropy nb_threads)
entropy="0.4"				# Randomness in the calculation time
nb_threads="seq. over. `seq 2 8`"

## Run-time settings
run=(count try)
count="100000000 200000000"		# amount of data to be written to main memory
try=`seq 1 10`				# Number of different run per setting

## Run-time data
output_columns="thread start_time_sec start_time_nsec stop_time_sec stop_time_nsec thread_start_sec thread_start_nsec thread_stop_sec thread_stop_nsec"

## Aliases for settings or columns (matching index value starting at 0)
alias_count="10^{8} 2_10^8"
alias_thread="SEQ Thread_1 Thread_2 Thread_3 Thread_4 Thread_5 Thread_6 Thread_7 Thread_8"
alias_try="1 2 3 4 5 6 7 8 9 10"
