#!/bin/bash

#     Copyright 2011 Nicolas Melot
# 
#    Nicolas Melot (nicolas.melot@liu.se)
# 
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
# 
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Variable and alias name format:
# Forbidden character: !=<>:&|()+-*/;"' (may be more characters raising issues. Stick to a-zA-Z0-9_~{}^ and ' '
# Special characters: ~^{}  ~ is replaced by _ and are interpreted for exposants and indices as latex does.
#	Note   : this replacement is performed only on aliases
# Must not begin with a digit 0-9 or a point '.' and must not start or finish with a space ' '.

# Never use these names for run or compile features (please report other problematic names)
# count

## Compile-time settings
compile=(entropy nb_threads)
entropy="0.4"				# Randomness in the calculation time
nb_threads="seq. over. `seq 2 8`"

## Run-time settings
run=(count try)
count="100000000 200000000"		# amount of data to be written to main memory
try=`seq 1 3`				# Number of different run per setting

## Run-time data
output_columns="thread start_time_sec start_time_nsec stop_time_sec stop_time_nsec thread_start_sec thread_start_nsec thread_stop_sec thread_stop_nsec comment1 comment2"

## Never allow experiments involving a try number two when exactly 2 threads are involved
restrict='! ( match(try, "^2$") && match(nb_threads, "^3$") )'

## Give human-friendly aliases for every value of variables
## Order variables occurences
## Skip the label if all you want is to arrange occurences in order, and use these occurrences name as labels
## Note that all labels are left and right trimmed
labels_nb_threads="seq.: Sequential; over.: Overhead;2;3;4"
labels_count="100000000:10^8; 200000000: 20^8"
labels_thread="0:Thread 1 (seq.); 1: Thread 1; 2: Thread 2; 3: Thread 3; 4: Thread 4"
labels_columns="entropy: Entropy; nb_threads: Number of threads; count: Number of iterations; try: Attempt; thread: Thread;"
